[data]
kitId=2

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; upload_protocol = espota ; Caso use OTA
; upload_port = iikit${data.kitId}.local
build_src_filter = +<esp2.cpp>
lib_deps =
    adafruit/Adafruit ADS1X15 @ ^2.5.0
    adafruit/Adafruit SSD1306 @ ^2.5.0
    adafruit/Adafruit GFX Library @ ^1.11.0
    adafruit/Adafruit BusIO @ ^1.16.0