[data]
kitId=2

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; upload_protocol = espota ; Caso use OTA
; upload_port = iikit${data.kitId}.local
lib_deps = josuemorais/iikit_lib@^0.0.21
; lib_deps = file://C:\SourceCode\iikit_lib 
build_src_filter = +<esp0.cpp>